BOARD_TAG    = nano
MCU = atmega328p

ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial FastLed stringQueue lsem SimpleTimer EEPROM Adafruit_Sensor Low-Power DHT-sensor-library DHTsensor HCSR04sensor NonBlockingRTTTL/src Arduino-MedianFilter/src  RtttlTrackerList U8g2_Arduino SPI Wire

USER_LIB_PATH = $(realpath ../SCS/arduino)

AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_DIR=/home/jes/arduino-1.8.13
ARDMK_DIR=/usr/share/arduino
include $(ARDMK_DIR)/Arduino.mk



