BOARD_TAG    = nano
MCU = atmega328p

ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial DFPlayer-Mini-mp3/DFPlayer_Mini_Mp3

USER_LIB_PATH = $(realpath ../..)

AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_DIR=/home/jes/arduino-1.8.13
ARDMK_DIR=/usr/share/arduino


include $(ARDMK_DIR)/Arduino.mk



