BOARD_TAG    = nano
MCU = atmega328p

ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial DFRobotDFPlayerMini

USER_LIB_PATH = $(realpath ../..)

#AVRDUDE_ARD_BAUDRATE = 115200

AVRDUDE_ARD_BAUDRATE = 57600

ARDUINO_DIR=/home/${USER}/arduino-1.8.13
ARDMK_DIR=/usr/share/arduino


include $(ARDMK_DIR)/Arduino.mk



