BOARD_TAG    = nano
MCU = atmega328p

ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial SPI Wire RTClib Adafruit-GFX-Library Adafruit_SSD1306 Adafruit_BusIO

USER_LIB_PATH = $(realpath ../../../)

AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_DIR=/home/jes/arduino-1.8.13
ARDMK_DIR=/usr/share/arduino


#CPPFLAGS+= -DLAMP_ENABLE_LSLIB


include $(ARDMK_DIR)/Arduino.mk



