BOARD_TAG    = nano
MCU = atmega328p
ARDUINO_PORT = /dev/ttyUSB0
#ARDUINO_LIBS = SoftwareSerial Adafruit_Sensor Low-Power DHT-sensor-library DHTsensor
ARDUINO_LIBS = SoftwareSerial Adafruit_Sensor Low-Power DHT-sensor-library

USER_LIB_PATH = $(realpath ../../)

AVRDUDE_ARD_BAUDRATE = 57600

ARDUINO_DIR  = /usr/share/arduino

include $(ARDUINO_DIR)/Arduino.mk


