BOARD_TAG    = nano
MCU = atmega328p

ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial Adafruit_Sensor DHT-sensor-library

USER_LIB_PATH = $(realpath ../../)

AVRDUDE_ARD_BAUDRATE = 57600
#AVRDUDE_ARD_BAUDRATE = 38400

#ARDMK_DIR     = /home/jes/arduino-1.8.13
#AVR_TOOLS_DIR = /home/jes/arduino-1.8.13
#ARDUINO_DIR  = /home/jes/arduino-1.8.13
#ARDUINO_DIR   = /usr/share/arduino


ARDUINO_DIR=/home/jes/arduino-1.8.13
#AVR_TOOLS_DIR=/home/jes/arduino-1.8.13/hardware/tools/avr
#AVR_TOOLS_DIR=/usr/share/arduino/hardware/tools/avr

#ARDUINO_LIB_PATH = /home/jes/arduino-1.8.13/libraries
#ARDUINO_PLATFORM_LIB_PATH = /home/jes/arduino-1.8.13/hardware/arduino/avr/libraries


#   AVR_TOOLS_DIR = /usr
ARDMK_DIR=/usr/share/arduino
include $(ARDMK_DIR)/Arduino.mk


