#!/bin/bash 
# TODO: make a python with flask a integrable web dump info
# TODO get services from autogenerated form installing...
SERVICES_LIST="smartCam picam timelapse mjpg-streamer telegramBOT netMonitor wvdial"

echo "================================"
echo "==== SYSTEM SETTINGS REPORT ===="
echo "================================"

echo "----------"
echo "  MEMORY"
echo "----------"
free

echo "----------"
echo "  CPU "
echo "----------"
top -o %CPU -n 1 -b  | head -15

echo "----------"
echo "  DISK "
echo "----------"
df -H

echo "-------------"
echo "  NETOWRKING "
echo "-------------"
ifconfig
iwconfig
ip r

# TODO  bandwith

echo "----------------"
echo "  KEY SERVICES "
echo "----------------"

for item in $SERVICES_LIST; do
      echo -n "Service $item ... "
      systemctl is-active $item.service
done




